name: Setup
on: [push, workflow_dispatch]
jobs:
   lint:
     runs-on: ubuntu-latest
     steps:
       - name: Add Respository
         uses: actions/checkout@v3
       - name: Call Lint Command
         run: npm run lint
         working-directory: 04 Practice Project (Start)
   test:
     runs-on: ubuntu-latest
     steps:
       - name: Add Respository
         uses: actions/checkout@v3
       - name: Call Test Command
         run: npm run test
         working-directory: 04 Practice Project (Start)
   build:
     needs: test
     runs-on: ubuntu-latest
     steps:
       - name: Add Respository
         uses: actions/checkout@v3
       - name: Call Build Command
         run: npm run build
         working-directory: 04 Practice Project (Start)